//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.09 at 10:10:23 AM CST 
//


package com.elong.nb.model.elong;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import com.alibaba.fastjson.annotation.JSONField;


/**
 * <p>Java class for Location complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Location">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="WaterMark" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Location", propOrder = {
    "url",
    "waterMark",
    "sizeType"
})
public class Location {

	@JSONField(name = "Url")
	@XmlAttribute(name = "Url")
    protected String url;
	
    @XmlAttribute(name = "WaterMark")
    @JSONField(name = "WaterMark")
    protected String waterMark;
    
    @XmlAttribute(name = "SizeType")
    @JSONField(name = "SizeType")
    protected int sizeType;

	/**   
	 * 得到url的值   
	 *   
	 * @return url的值
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * 设置url的值
	 *   
	 * @param url 被设置的值
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**   
	 * 得到waterMark的值   
	 *   
	 * @return waterMark的值
	 */
	public String getWaterMark() {
		return waterMark;
	}

	/**
	 * 设置waterMark的值
	 *   
	 * @param waterMark 被设置的值
	 */
	public void setWaterMark(String waterMark) {
		this.waterMark = waterMark;
	}

	/**   
	 * 得到sizeType的值   
	 *   
	 * @return sizeType的值
	 */
	public int getSizeType() {
		return sizeType;
	}

	/**
	 * 设置sizeType的值
	 *   
	 * @param sizeType 被设置的值
	 */
	public void setSizeType(int sizeType) {
		this.sizeType = sizeType;
	}


}
